config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'books#index'
  resources :genres
  resources :users
  resources :authors
  resources :books
  resources :deals
  resources :reviews
  resource :profile, only: [:show]
  get '/home', to: 'books#index'
  get '/search_book', to: 'books#search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Defines the root path route ("/")
  # root "posts#index"
  end
  end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books

  validates :title, presence: true, uniqueness: true

  def self.add_genre(title)
    genre = Genre.new(title:)
    if genre.valid?
      genre.save
      Genre.last
    else
      puts genre.errors.full_messages
      nil
    end
  end

  def self.update_genre(title, id)
    genre = Genre.find(id)
    new_genre = Genre.new(title:)
    if new_genre.valid?
      genre.update(title:)
      Genre.find(id)
    else
      puts new_genre.errors.full_messages
      nil
    end
  end

  def self.delete_genre_id(id)
    genre = Genre.find(id)
    genre.books.clear
    genre.delete
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_genre, only: %i[show edit update destroy]
  before_action :authorize_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show; end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: 'Genre was successfully created.'
    else
      flash.now[:alert] = 'This genre already exists!'
      render :new
    end
  end

  def edit; end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: 'Genre was successfully updated.'
    else
      flash.now[:alert] = 'This genre already exists!'
      render :edit
    end
  end

  def destroy
    Genre.delete_genre_id(params[:id])
    redirect_to genres_path, notice: 'Genre was successfully destroyed.'
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:title)
  end

  def authorize_admin!
    unless current_user.admin?
      flash[:alert] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end
end

app/views/genres/edit.html.erb
<br>
<div class="container">
  <% if user_signed_in? %>
    <h1><%= t('titles.edit_genre', title: @genre.title) %></h1>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= form_with(model: @genre, url: genre_path) do |form| %>

      <p>
        <%= form.label t('forms.labels.genre_title') %><br>
        <%= form.text_field :title %>
      </p>

      <%= form.hidden_field :id, value: @genre.id %>
      <p>
        <%= form.submit t('forms.submit.edit_genre') %>
      </p>
    <% end %>
  <% else %>
    <h1><%= t('titles.sign_in') %></h1>
  <% end %>
</div>

app/views/genres/index.html.erb
<% if user_signed_in? %>
  <div class="container mt-5">
    <%= image_tag 'banner_genres.jpg', class: 'img-fluid banner-image', style: "height: 365px;" %>
    <h1 class="text-center mt-2"><%= t('titles.genres') %></h1>
    <div class="text-center mb-4">
      <%= link_to t('links.back_to_advertisements'), home_path, class: "btn btn-secondary" %>
    </div>
    <div class="row">
      <% @genres.each do |genre| %>
        <div class="col-md-4 mb-4">
          <div class="card genre-card">
            <%= image_tag_ignore_case("#{genre.title}.jpg", class: 'card-img-top genre-image', alt: genre.title) %>
            <div class="card-body">
              <% if current_user.admin? %>
                <h5 class="card-title"><%= link_to genre.title, genre_path(genre), class: "genre-link" %></h5>
              <% else %>
                <h5 class="card-title"><%= genre.title %></h5>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if current_user.admin? %>
      <div class="text-center mt-4">
        <%= link_to t('buttons.add_new_genre'), new_genre_path, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
<% else %>
  <h1><%= t('titles.sign_in') %></h1>
<% end %>

app/views/genres/new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if user_signed_in? %>
  <div class="container">
    <h1><%= t('titles.add_new_genre') %></h1>
    <%= form_with(model: @genre, url: genres_path) do |form| %>
      <p>
        <%= form.label t('forms.labels.genre_title') %><br>
        <%= form.text_field :title %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
<% else %>
  <h1><%= t('titles.sign_in') %></h1>
<% end %>

app/views/genres/show.html.erb
<br>
<div class="container">
  <% if user_signed_in? %>
    <h1><%= t('titles.genre_title') %>: <%= @genre.title %></h1>
  <% else %>
    <h1><%= t('titles.sign_in') %></h1>
  <% end %>

  <%= link_to t('links.back_to_genres_list'), genres_path, class: "btn btn-outline-dark" %><br>
  <% if user_signed_in? %>
    <%= link_to t('buttons.edit_genre'), edit_genre_path, class: "btn btn-outline-dark" %>
    <%= button_to t('buttons.delete_genre'), @genre, method: :delete %>
  <% end %>
</div>