config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'books#index'
  resources :genres
  resources :users
  resources :authors
  resources :books
  resources :deals
  resources :reviews
  resource :profile, only: [:show]
  get '/home', to: 'books#index'
  get '/search_book', to: 'books#search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Defines the root path route ("/")
  # root "posts#index"
  end
  end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, presence: true, uniqueness: true

  def self.add_author(name)
    author = Author.new(name:)
    if author.valid?
      author.save
      Author.last
    else
      puts author.errors.full_messages
      nil
    end
  end

  def self.update_author(id, name)
    author = Author.find(id)
    new_author = Author.new(name:)
    if new_author.valid?
      author.update(name:)
      Author.find(id)
    else
      puts new_author.errors.full_messages
      nil
    end
  end

  def self.delete_author_id (id)
    author = Author.find(id)
    author.books.clear
    author.delete
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit]
  before_action :authenticate_user!
  before_action :authorize_admin!, only: [:new, :create, :edit, :destroy]
  before_action :set_locale

  def set_locale
    if params[:locale].blank?
      redirect_to "/#{extract_locale_from_accept_language_header}"
    else
      I18n.locale = params[:locale]
    end
  end

  def index
    @authors = Author.all
  end

  def show; end

  def new
    @author = Author.new
  end

  def create
    @author = Author.add_author(author_params[:name])
    if @author
      redirect_to @author
    else
      flash.now[:alert] = 'This author already exists!'
      @author = Author.new
      render :new
    end
  end

  def edit; end

  def update
    @author = Author.update_author(params[:id], author_params[:name])
    if @author
      redirect_to @author
    else
      flash.now[:alert] = 'This author already exists!'
      set_author
      render :edit
    end
  end

  def destroy
    Author.delete_author_id(params[:id])
    redirect_to authors_path
  end

  def authorize_admin!
    unless current_user.admin?
      flash[:alert] = "Ви не маєте доступу до цієї сторінки."
      redirect_to root_path
    end
  end


  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/views/authors/edit.html.erb
<br>
<div class="container">
  <% if user_signed_in? %>
    <h1><%= t('titles.edit_author', author: @author.name) %></h1>
  <% else %>
    <h1><%= t('titles.sign_in') %></h1>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: @author, url: author_path) do |form| %>
      <p>
        <%= form.label :name, t('forms.labels.name') %><br>
        <%= form.text_field :name %>
      </p>
      <p>
        <%= form.submit t('forms.submit.edit_author') %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/authors/index.html.erb
<div class="container mt-5">
  <%= image_tag 'banner_author.jpg', class: 'img-fluid banner-image', style: "height: 365px;" %>
  <h1 class="text-center mt-4"><%= t('titles.all_authors') %></h1>
  <div class="text-center mb-4">
    <%= link_to t('links.back_to_home'), home_path, class: "btn btn-secondary" %>
  </div>

  <% if user_signed_in? %>
    <div class="row">
      <% @authors.each do |author| %>
        <div class="col-md-4 mb-4">
          <div class="author-card card">
            <%= image_tag 'author.jpg', class: "card-img-top", style: "width:100%; height: 250px;" %>
            <div class="card-body text-center">
              <% if current_user.admin? %>
                <h3 class="card-title"><%= link_to author.name, author_path(author) %></h3>
              <% else %>
                <h3 class="card-title"><%= author.name %></h3>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if current_user.admin? %>
      <div class="text-center mt-4">
        <%= link_to t('links.add_new_author'), new_author_path, class: "btn btn-success" %>
      </div>
    <% end %>
  <% else %>
    <h1 class="text-center"><%= t('titles.sign_in') %></h1>
  <% end %>
</div>

app/views/authors/new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if user_signed_in? %>
  <%= form_with(model: @author, url: authors_path) do |form| %>
    <div class="container">
      <br>
      <h1><%= t('titles.add_new_author') %></h1>
      <p>
        <%= form.label t('labels.enter_name') %><br>
        <%= form.text_field :name %>
      </p>
      <br>
      <p>
        <%= form.submit t('forms.submit.add_author') %>
      </p>
    </div>
  <% end %>
<% else %>
  <h1><%= t('titles.sign_in') %></h1>
<% end %>

app/views/authors/show.html.erb
<br>
<div class="container">
  <% if user_signed_in? %>
    <h1><%= t('titles.author_name', name: @author.name) %></h1>
  <% else %>
    <h1><%= t('titles.sign_in') %></h1>
  <% end %>

  <%= link_to t('links.back_to_authors_list'), authors_path, class: "btn btn-outline-dark" %><br>

  <% if user_signed_in? %>
    <%= link_to t('links.edit_author'), edit_author_path, class: "btn btn-outline-dark"%>
    <%= button_to t('buttons.delete_author'), author_path, method: :delete, data: { confirm: t('messages.confirm_delete_author') } %>
  <% end %>
</div>