config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'books#index'
  resources :genres
  resources :users
  resources :authors
  resources :books
  resources :deals
  resources :reviews
  resource :profile, only: [:show]
  get '/home', to: 'books#index'
  get '/search_book', to: 'books#search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Defines the root path route ("/")
  # root "posts#index"
  end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit]

  def index
    @reviews = Review.all
  end

  def show; end

  def new
    @review = Review.new
  end

  def create
    @review = Review.add_review(review_params[:title], review_params[:descr], review_params[:user_id])
    if @review
      redirect_to @review
    else
      flash.now[:alert] = 'This review already exists!'
      @review = Author.new
      render :new
    end
  end

  def edit; end

  def update
    @review = Review.update_review(params[:id], review_params[:title], review_params[:descr], review_params[:user_id])
    if @review
      redirect_to @review
    else
      flash.now[:alert] = 'This review already exists!'
      set_review
      render :edit
    end
  end

  def destroy
    Review.delete_review_id(params[:id])
    redirect_to reviews_path
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :descr, :user_id)
  end
end

app/views/reviews/edit.html.erb
<h1><%= t('titles.edit_review') %></h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @review, url: review_path(@review), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @users, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.collection_select :library_id, @libraries, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<h1><%= t('titles.reviews') %></h1>
<%= link_to t('links.back'), home_path %>
<table>
  <thead>
  <tr>
    <th><%= t('labels.user') %></th>
    <th><%= t('labels.library') %></th>
    <th><%= t('labels.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.user.name %></td>
      <td>
        <%= link_to t('links.show'), review %>
        <%= link_to t('links.edit'), edit_review_path(review) %>
        <%= button_to t('buttons.destroy'), review, method: :delete %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new_review'), new_review_path %>

app/views/reviews/new.html.erb
<h1><%= t('titles.new_review') %></h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @review, url: reviews_path) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :descr %>
    <%= form.text_area :descr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<h1><%= t('titles.reader_card_details') %></h1>

<table>
  <tr>
    <td><strong><%= t('labels.user') %>:</strong></td>
    <td><%= @reader_card.user.name %></td>
  </tr>
  <tr>
    <td><strong><%= t('labels.library') %>:</strong></td>
    <td><%= @reader_card.library.name %></td>
  </tr>
  <tr>
    <td><strong><%= t('labels.books') %>:</strong></td>
    <td>
      <% if @reader_card.books.any? %>
        <ul>
          <% @reader_card.books.each do |book| %>
            <li><%= book.title %></li>
          <% end %>
        </ul>
      <% else %>
        <p><%= t('messages.no_books_yet') %></p>
      <% end %>
    </td>
  </tr>
</table>

<p><%= link_to t('links.edit'), edit_reader_card_path(@reader_card) %></p>
<p><%= link_to t('links.back'), reader_cards_path %></p>