config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'books#index'
  resources :genres
  resources :users
  resources :authors
  resources :books
  resources :deals
  resources :reviews
  resource :profile, only: [:show]
  get '/home', to: 'books#index'
  get '/search_book', to: 'books#search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Defines the root path route ("/")
  # root "posts#index"
  end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookSphere</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbo-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&family=Playfair+Display:wght@700&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
  <%= javascript_importmap_tags %>

  <!-- Favicon Links -->
  <link rel="icon" type="image/png" sizes="192x192" href="<%= asset_path('android-chrome-192x192.png') %>">
  <link rel="icon" type="image/png" sizes="512x512" href="<%= asset_path('android-chrome-512x512.png') %>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path('apple-touch-icon.png') %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path('favicon-16x16.png') %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path('favicon-32x32.png') %>">
  <link rel="icon" type="image/x-icon" href="<%= asset_path('favicon.ico') %>">
  <link rel="manifest" href="<%= asset_path('site.webmanifest') %>">
</head>
<body class="<%= content_for?(:page_class) ? yield(:page_class) : 'default-background' %>">
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to t('titles.book_sphere'), home_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'English', url_for(locale: 'en'), class: "nav-link #{'active' if I18n.locale == :en}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Українська', url_for(locale: 'uk'), class: "nav-link #{'active' if I18n.locale == :uk}" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to t('links.announcements'), books_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to t('links.authors'), authors_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('links.users'), users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('links.genres'), genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('links.add_announcement'), new_book_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('links.my_profile'), profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to t('buttons.sign_out'), destroy_user_session_path, method: :delete, class: "nav-link btn btn-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('buttons.sign_in'), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div id="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash <%= 'flash-notice' if type == 'notice' %> <%= 'flash-alert' if type == 'alert' %>">
      <%= message %>
    </div>
  <% end %>
</div>

<div class="<%= content_for?(:container_class) ? yield(:container_class) : 'container mt-4' %>">
  <%= yield %>
</div>

<script>
    document.addEventListener('turbo:load', function()  {
        const flashes = document.querySelectorAll('.flash');
        flashes.forEach(flash => {
            setTimeout(() => {
                flash.style.transition = 'opacity 0.5s';
                flash.style.opacity = '0';
                setTimeout(() => flash.remove(), 500); // Полностью удаляет элемент из DOM после исчезновения
            }, 3000);
        });
    });
</script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var alerts = document.querySelectorAll('.alert');
        alerts.forEach(function(alert) {
            setTimeout(function() {
                alert.style.display = 'none';
            }, 3000);
        });
    });
</script>
</body>
</html>